import NextHead from "next/head";
import React from "react";
import { useTranslation } from "react-i18next";

interface Props {}

const Head: React.FC<Props> = () => {
  const { t } = useTranslation();

  return (
    <NextHead key="the-head">
      <title>{t("general.title")}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
        rel="stylesheet"
      />
    </NextHead>
  );
};

export default Head;
