import NextHead from "next/head";
import React from "react";

interface Props {}

const Head: React.FC<Props> = () => {
  return (
    <NextHead key="the-head">
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  );
};

export default Head;
